### PR TITLE
Remove unsafeCoerce from appendIndices and fix tests with GHC 9.0.1

### LINKED ISSUE #396: Tests fail with 9.0.1 because of unsafeEqualityProof
15 of tests fail with GHC 9.0.1, mostly because of unsafeEqualityProof, e.g.

```haskell
        tests/Optics/Tests/Utils.hs:56:
        tests/Optics/Tests/Labels/TH.hs:61:20: label5lhs ==- label5rhs failed:            
            LHS:                                                                          
                label5lhs = label5lhs_szze `cast` <Co:31>                                 
                                                                                          
                label5lhs_szze                                                            
                  = \ @a @b s name_ age_ fishName_ pets_ ->                               
                      case unsafeEqualityProof of { UnsafeRefl co2 ->
                      case s of { Human x1_af3x x2_af3y x3_af3z x4_af3A ->
                      (Human
                         name_
                         age_
                         (case x3_af3z of {
                            GoldFish x1_aeS2 -> GoldFish fishName_;
                            Herring x1_aeS4 -> Herring fishName_
                          })
                         pets_)
                      `cast` <Co:4>
                      }
                      }
                
            RHS:
                label5rhs
                  = \ @a @b s name_ age_ fishName_ pets_ ->
                      case s of { Human ds_dpF7 ds_dpF8 ds_dpF9 ds_dpFa ->
                      Human
                        name_
                        age_
                        (case ds_dpF9 of {
                           GoldFish ds_dpEY -> GoldFish fishName_;
                           Herring ds_dpEZ -> Herring fishName_
                         })
                        pets_
                      }
```

Does anyone know why are these in a release? I know they used to show in GHC compiled from git in the past, but they didn't in releases.

### PR DESCRIPTION
**Pull request by arybczak**
Fixes #396.

This doesn't slow compilation, I tested with a big project.

### CODE REVIEW

**Comment by phadej** [comment]
Let's see after `INLINE`s are removed.

**Comment by arybczak** [comment]
I also tried that with the inlineless branch and it was fine 👍

File: optics-core/src/Optics/Internal/Optic/TypeLevel.hs [hunk 1]
```diff
@@ -98,37 +96,34 @@ instance CurryCompose xs => CurryCompose (x ': xs) where
 ----------------------------------------
 -- Indices
 
+-- | Tagged version of 'Data.Type.Equality.(:~:)' for carrying evidence that two
+-- index lists in a curried form are equal.
+data IxEq i is js where
```
Comment (phadej) [inline optics-core/src/Optics/Internal/Optic/TypeLevel.hs:101]: This is nice.

File: optics-core/src/Optics/Internal/Optic.hs [hunk 2]
```diff
@@ -115,7 +114,7 @@ castOptic (Optic o) = Optic (cast o)
 -- indexed, the composition preserves all the indices.
 --
 infixl 9 %
-(%) :: (Is k m, Is l m, m ~ Join k l, ks ~ Append is js)
+(%) :: (Is k m, Is l m, m ~ Join k l, AppendIndices is js, ks ~ Append is js)
```
Comment (adamgundry) [inline optics-core/src/Optics/Internal/Optic.hs:117]: I think this is generally a good idea, but the only thing that is a slight shame is making the type of `%` more complicated, with `AppendIndices` potentially showing up in inferred types. Perhaps it is worth making `AppendIndices` takes `ks` as a parameter so that `AppendIndices is js ks` can imply `ks ~ Append is js`?

Comment (phadej) [reply optics-core/src/Optics/Internal/Optic.hs:117]: One could maybe get rid of `Append` family all together, by having 

```diff
-appendIndices :: IxEq i (Curry xs (Curry ys i)) (Curry (Append xs ys) i)
+appendIndices :: IxEq i (Curry xs (Curry ys i)) (Curry zs i)
```

... but I guess we cannot as there is no sane way to break functional dependencies in GHCs.

Comment (arybczak) [reply optics-core/src/Optics/Internal/Optic.hs:117]: > Perhaps it is worth making AppendIndices takes ks as a parameter

That's what I've done in #353, but then you pointed out [here](https://github.com/well-typed/optics/pull/353#issuecomment-687915488) that GHC expands `ks` to be `Append is js` and removing it would be better ;)

File: optics-core/src/Optics/Internal/Optic/TypeLevel.hs [hunk 3]
```diff
@@ -107,23 +107,20 @@ data IxEq i is js where
...
 --    where f = (->)
 -- @
-class AppendIndices xs ys where
-  appendIndices :: IxEq i (Curry xs (Curry ys i)) (Curry (Append xs ys) i)
+class AppendIndices xs ys ks | xs ys -> ks where
+  appendIndices :: IxEq i (Curry xs (Curry ys i)) (Curry ks i)
 
--- | If we know the second list is empty, we can pick the first list without
--- knowing anything about it, hence the instance is marked as INCOHERENT.
-instance {-# INCOHERENT #-} AppendIndices xs '[] where
```
Comment (phadej) [inline optics-core/src/Optics/Internal/Optic/TypeLevel.hs:112]: Oh, I thought that `FunctionalDependencies` would choke on this? Is `INCOHERENT` lifting that somehow?

File: optics-core/src/Optics/Internal/Optic.hs (hunk 2 above)
Comment (arybczak) [reply optics-core/src/Optics/Internal/Optic.hs]: > One could maybe get rid of Append family all together

I tried that and looks like it works, so I re-added the third parameter and removed dependence on `Append`.

File: optics-core/src/Optics/Internal/Optic/TypeLevel.hs [hunk 4]
```diff
@@ -98,37 +96,31 @@ instance CurryCompose xs => CurryCompose (x ': xs) where
...
+-- immediately.
+instance {-# INCOHERENT #-} AppendIndices xs '[] xs where
+  appendIndices = IxEq
+
+instance AppendIndices '[] ys ys where
+  appendIndices = IxEq
+
+instance AppendIndices xs ys ks => AppendIndices (x ': xs) ys (x ': ks) where
+  appendIndices :: forall i. IxEq i (Curry (x ': xs) (Curry ys i)) (Curry (x ': ks) i)
+  appendIndices | IxEq <- appendIndices @xs @ys @ks @i = IxEq
```
Comment (phadej) [inline optics-core/src/Optics/Internal/Optic/TypeLevel.hs:123]: This looks very nice. :+1:

**Comment by arybczak** [comment]
It's worth noting that due to `%` being `infixl` when composing multiple indexed optics the behaviour of AppendIndices is quadratic :thinking: 

Though that shouldn't be a problem in practice since I doubt anyone uses >5 indices in a single pipeline.

**Comment by phadej** [comment]
re quadratic: wasn't that the case with `Append` also?

**Comment by arybczak** [comment]
Oh, you're right. I thought `unsafeCoerce` saved us there before, but indeed `Append` was still quadratic.

File: optics-core/src/Optics/Internal/Optic/TypeLevel.hs (hunk 3 above)
Comment (arybczak) [reply optics-core/src/Optics/Internal/Optic/TypeLevel.hs:112]: It's not INCOHERENT, it's just that the consistency check for fundeps is quite lenient.
