### PR TITLE
Stop picking the catch-all JoinKinds instance if arguments match

### LINKED ISSUE #423: Misleading error message from JoinKinds
With 0.4 and current HEAD:
```
ghci> :t castOptic @A_Setter @A_Setter (traversed % _1)

<interactive>:1:42: error:
    • A_Traversal cannot be composed with A_Lens
    • In the third argument of ‘castOptic’, namely ‘(traversed % _1)’
      In the expression: castOptic @A_Setter @A_Setter (traversed % _1)
```

Oops! I think what is going on here is that we get a constraint `JoinKinds A_Traversal A_Lens A_Setter` which of course does not match the instance `JoinKinds A_Traversal A_Lens A_Traversal`, so the catch-all error instance fires. Ideally we would have two different errors, one for "this composition doesn't make sense" and another for "this composition makes sense, but produces an optic of a different kind to that expected by the context".

### PR DESCRIPTION
**Pull request by arybczak**
Fixes #423 (to an extent).

Simpler than #424, but should make the situation strictly better.

### CODE REVIEW

**Comment by arybczak** [comment]
Uh, the fragility of these inspection tests is rather sad.

I also removed the `let res :: JoinKinds A_Lens A_Prism k => Proxy k; res = Proxy` doctest from the `Optics` module because it started triggering a warning with this PR. It's fixable, but it no longer works as expected with GHC 9.2 anyway.

File: codegen/Subtypes.hs [hunk 1]
```diff
@@ -126,10 +126,12 @@ genJoin = either (fail . show) id $ runG opticsKind $ \g -> do
...
   where
     joinInstance k l m = unwords
-      [ "instance JoinKinds"
+      [ "instance k ~"
+      , leftpad $ show m
+      , "=> JoinKinds"
       , leftpad $ show k
       , leftpad $ show l
-      , leftpad $ show m
+      , "k"
```
Comment (phadej) [inline codegen/Subtypes.hs:134]: Clever :)

**Review by phadej — APPROVED** [review]
